version: '3.8'

services:
  hotel-db:
    image: postgres:15
    container_name: hotel-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - hotel_system_postgres_data:/var/lib/postgresql/data
    networks:
      - hotel-net

  hotel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-api
    depends_on:
      - hotel-db
    environment:
      DB_HOST: hotel-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8090:8090"
    networks:
      - hotel-net

volumes:
  hotel_system_postgres_data:

networks:
  hotel-net:
    driver: bridge
