spring.application.name=hotel-manage-system

# SERVER
server.port=8091

# DATASOURCE
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SECURITY
app.jwt.secret=${JWT_SECRET}
# 15 minutes
app.jwt.expiration-ms=900000

# oauth2
app.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
app.oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}