-- DATOS DE CATÁLOGO
INSERT INTO roles (name) VALUES ('ROLE_ADMIN'), ('ROLE_RECEPCIONISTA'), ('ROLE_LIMPIEZA'), ('ROLE_CLIENTE');
INSERT INTO room_statuses (name) VALUES ('DISPONIBLE'), ('OCUPADA'), ('MANTENIMIENTO');
INSERT INTO reservation_statuses (name) VALUES ('PENDIENTE'), ('CONFIRMADA'), ('CANCELADA'), ('COMPLETADA');
INSERT INTO payment_statuses (name) VALUES ('PENDIENTE'), ('EXITOSO'), ('FALLIDO');
INSERT INTO payment_methods (name) VALUES ('STRIPE'), ('EFECTIVO'), ('TRANSFERENCIA'), ('CORTESIA'), ('CREDITO'), ('DEBITO');

-- PERMISOS BASE
INSERT INTO permissions (name) VALUES
  ('USER_VIEW'),
  ('USER_CREATE'),
  ('USER_EDIT'),
  ('USER_DELETE'),
  ('ROOM_VIEW'),
  ('ROOM_CREATE'),
  ('ROOM_EDIT'),
  ('ROOM_DELETE'),
  ('ROOM_PRICE_MANAGE'),
  ('RESERVATION_VIEW'),
  ('RESERVATION_CREATE'),
  ('RESERVATION_EDIT'),
  ('RESERVATION_CANCEL'),
  ('PAYMENT_VIEW'),
  ('PAYMENT_PROCESS'),
  ('INVOICE_VIEW'),
  ('INVOICE_GENERATE'),
  ('CONFIG_UPDATE'),
  ('VIEW_AUDIT_LOG'),
  ('ASSIGN_ROLES');

-- ASIGNAR TODOS LOS PERMISOS AL ROL ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT
  (SELECT id FROM roles WHERE name = 'ROLE_ADMIN'),
  p.id
FROM permissions p;
